### ISSUE TITLE
No module named 'winnt'

### ISSUE THREAD

**Issue by Brobeda** [naturalstupid/PyJHora#10]
Sorry, I'm new to github, no idea how to point to the code.

src/jhora/ui/chakra.py

from winnt import ACCESS_PROPERTY_GUID

Error:
  File "C:\Users\Bob\AppData\Local\Programs\Python\Python312\Lib\site-packages\jhora\ui\chakra.py", line 6, in <module>
    from winnt import ACCESS_PROPERTY_GUID
ModuleNotFoundError: No module named 'winnt'

Solution:
remove the line, ACCESS_PROPERTY_GUID is not accessed

**Comment by naturalstupid** [comment]
Please remove for now in your local code. As I use Eclipse IDE - sometimes it may add some unwanted imports like this. I have removed it from the next version. Thanks for pointing out.
