### ISSUE TITLE
Request to add me as a collaborator

### ISSUE THREAD

**Issue by Akilesh1989** [naturalstupid/PyJHora#3]
Hi @naturalstupid can you add me as a collaborator?

The major change I have made is to add instructions, move files around to make Pyhora UI work in a macbook and I have detailed instructions on how to do it as well.

**Comment by naturalstupid** [comment]
I work in my computer's Eclipse IDE and not on github. I just upload latest working version onto github. I regret I am not familiar with github features. I would appreciate instructions to add you as colloborator.
Meanwhile I had fixed some major issues, and added several new dhasas and my latest local version is 2.9.6 which I will soon upload. Thanks for the understanding.

**Comment by facemoon** [comment]
> Hi @naturalstupid can you add me as a collaborator?
> 
> The major change I have made is to add instructions, move files around to make Pyhora UI work in a macbook and I have detailed instructions on how to do it as well.

Namaste! You can make instructions for MacBook, I am a beginner and I can’t start, the error "Modulenotfounderror: No Module Named 'Hora' in Visual Studio Code is constantly emerging. Plz....

**Comment by krishnakanthpps** [comment]
@facemoon  you need to import the hora into code and it would solve it. it is a very simple error. Try running this on a venv and things should work easily.

**Comment by naturalstupid** [comment]
If anyone want to become collaborator - please let me know (with instructions how to add you)
