### ISSUE TITLE
Installation not success

### ISSUE THREAD

**Issue by ByteMyst** [naturalstupid/PyJHora#8]
Hi - I am trying to install the requirements mentioned in the file and it keep throwing error

ERROR: Invalid requirement: 'import swisseph as swe': Expected end or semicolon (after name and no valid version specifier)
    import swisseph as swe
           ^ (from line 13 of C:\Users\nitin\Downloads\requirements.txt)

ERROR: Could not find a version that satisfies the requirement os (from versions: none)

Kindly guide I am using Python latest version 3.13.x

**Comment by naturalstupid** [comment]
please try installing manually the packages listed in requirements.txt
